### ISSUE TITLE
store messages

### ISSUE THREAD

**Issue by mLuby** [hrx/slack-private-archiver#1] opened 2016-11-08 19:59 UTC

**Comment by cehsu** [comment] 2016-11-19 00:00
Postgres will be the source of truth for archived messages.  Still need to determine if we are going to use it as a traditional RDBMS, or use it’s newer document store feature.

**Comment by aeb0** [comment] 2016-11-19 06:06
@dting 
+1 for RDBMS

**Comment by aeb0** [comment] 2016-11-24 20:43
@mLuby seems like a duplicate of #4 ? Closing let me know if you disagree

**Closed as completed by aeb0** 2016-11-24 20:43 UTC
Labels: enhancement, help wanted, needs discussion
